n = input('Digite um número de 0 a 9999 para ver os digitos separados: ')
print('unidade: {}'.format(n[3]))
print('dezena: {}'.format(n[2]))
print('centena: {}'.format(n[1]))
print('milhar: {}'.format(n[0]))
